model:
  id: "my-model-id"
  user_id: "my-user-id"
  app_id: "my-app-id"
  model_type_id: "text-to-text"

build_info:
  python_version: "3.12"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: "1Gi"
  cpu_requests: "0.5"
  cpu_memory_requests: "512Mi"
  num_accelerators: 0
  accelerator_type: ["NVIDIA-*"]
  accelerator_memory: "1Gi"