model:
  app_id: local-dev-runner-app
  id: local-dev-model
  model_type_id: text-to-text
  user_id: srikanthbachala
build_info:
  python_version: '3.11'
inference_compute_info:
  cpu_limit: 50m
  cpu_memory: 250Mi
  num_accelerators: 0
